-include device/samsung/msm8226-common/BoardConfigCommon.mk

# inherit from the proprietary version
-include vendor/samsung/ms013g/BoardConfigVendor.mk

LOCAL_PATH := device/samsung/ms013g

# Vendor Init
TARGET_UNIFIED_DEVICE := true
TARGET_INIT_VENDOR_LIB := libinit_msm


# Custom relese tools for unified devices
TARGET_RELEASETOOLS_EXTENSIONS := device/samsung/ms013g

#bluetooth
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := $(LOCAL_PATH)/bluetooth

#TWRP
DEVICE_RESOLUTION := 720x1280
TW_IGNORE_MAJOR_AXIS_0 := true

VSYNC_EVENT_PHASE_OFFSET_NS := 0

# Board Partitions
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 576716800
BOARD_USERDATAIMAGE_PARTITION_SIZE := 209715200
BOARD_CACHEIMAGE_PARTITION_SIZE := 69206016
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_FLASH_BLOCK_SIZE := 512
TARGET_USERIMAGES_SPARSE_EXT_DISABLED := true
BOARD_USES_ALSA_AUDIO := true
